[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.82"
vec_n = { path = "../../vec_n" }
webgl = { path = "../../webgl" }

[profile.release]
opt-level = "s"